//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmos.DbStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        public int ID { get; set; }
        public Nullable<bool> DISABLE { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<System.DateTime> COMMUNICATION_DATE { get; set; }
        public string PHONE_DATA { get; set; }
        public Nullable<int> SUBSCRIBER_ID { get; set; }
        public string COMMENT { get; set; }
    }
}
